#!/bin/sh

if [ "run" = "$1" ]; then
  echo "starting service"
  hamidun
  exec nginx -g "daemon off;"
elif [ "reload" = "$1" ]; then
  echo "reloading service"
  hamidun
  exec nginx -s reload
else
  echo "use $0 start|reload"
fi
